// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryConfig = { 
/**
 * Unique within a satellite.
 */
id: string, 
/**
 * Usable capacity, in watt-hours.
 */
capacity_watt_hours: number, 
/**
 * Charge at the start of the simulation, as a fraction of capacity in `[0, 1]`.
 */
initial_state_of_charge: number, 
/**
 * Constant housekeeping load drawn by the rest of the spacecraft, in watts.
 */
load_watts: number, };
