// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static description of one telemetry channel, used to label plots.
 */
export type ChannelSpec = { 
/**
 * Unique within a satellite, e.g. `"main_battery.state_of_charge"`.
 */
id: string, 
/**
 * Human-readable name for the plot title.
 */
label: string, 
/**
 * Unit symbol for the axis, e.g. `"W"` or `"%"`.
 */
unit: string, };
