// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatteryConfig } from "./BatteryConfig";
import type { SolarPanelConfig } from "./SolarPanelConfig";

/**
 * Serializable description of a component, as authored in the UI.
 */
export type ComponentConfig = { "kind": "SolarPanel" } & SolarPanelConfig | { "kind": "Battery" } & BatteryConfig;
