// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentConfig } from "./ComponentConfig";

export type Satellite = { 
/**
 * Stable identifier, used to match results back to the UI list.
 */
id: string, name: string, 
/**
 * Two-line element set. The two element lines are separated by newlines;
 * a leading title line is tolerated and ignored.
 */
tle: string, components: Array<ComponentConfig>, };
