// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelemetryChannel } from "./TelemetryChannel";

/**
 * One satellite's simulated trajectory and telemetry.
 */
export type SatelliteResult = { id: string, name: string, 
/**
 * TEME positions in metres, flattened as `[x0, y0, z0, x1, y1, z1, ...]`.
 *
 * Flat rather than an array of objects: a three-orbit window at ten-second
 * steps is ~1600 samples per satellite, and this avoids allocating that
 * many JavaScript objects.
 */
positions_teme_meters: Array<number>, channels: Array<TelemetryChannel>, };
