// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Satellite } from "./Satellite";

export type SimulationConfig = { satellites: Array<Satellite>, 
/**
 * Start of the window, in Unix seconds.
 */
start_unix_seconds: number, 
/**
 * Length of the window, in seconds.
 */
duration_seconds: number, 
/**
 * Spacing between samples, in seconds.
 */
step_seconds: number, };
