// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SatelliteResult } from "./SatelliteResult";

/**
 * Simulated trajectories and telemetry for every satellite in the request.
 *
 * Every series is parallel to the same sample grid: entry `i` is at
 * `start_unix_seconds + i * step_seconds`.
 */
export type SimulationResult = { start_unix_seconds: number, step_seconds: number, sample_count: number, satellites: Array<SatelliteResult>, };
