// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SolarPanelConfig = { 
/**
 * Unique within a satellite.
 */
id: string, 
/**
 * Total array area, in square metres.
 */
area_square_meters: number, 
/**
 * Conversion efficiency, as a fraction in `[0, 1]`.
 */
efficiency: number, };
