// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelSpec } from "./ChannelSpec";

/**
 * One channel's full time series over the simulated window.
 *
 * `values` is parallel to the sample grid: entry `i` is at
 * `start_unix_seconds + i * step_seconds`.
 */
export type TelemetryChannel = { spec: ChannelSpec, values: Array<number>, };
